In [2]:
import numpy as np

We want our code to be as expressive as possible, and avoid loops at all cost!

**Broadcasting** in NumPy follows a strict set of rules to determine the interaction between two arrays. In simple cases, it closely follows our intuitions.

- 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
- 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [9]:
np.arange(3) + 5

array([5, 6, 7])

![broadcasting1](images/broadcasting1.png)

Sequence of changes:

- (3,) + ()    <- Original shapes
- (3,) + (1,)  <- As per rule 1 (add leading dimension to 2nd array)
- (3,) + (3,)  <- As per rule 2 (stretch 2nd array on axis 0)
- (3,)         <- Final shape of output

In [6]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

![broadcasting2](images/broadcasting2.png)

Sequence of changes:

- (3,3) + (3,)   <- Original shapes
- (3,3) + (1,3)  <- As per rule 1 (add leading dimension to 2nd array)
- (3,3) + (3,3)  <- As per rule 2 (stretch 2nd array on axis 0)
- (3,3)          <- Final shape of output

In [8]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![broadcasting3](images/broadcasting3.png)

Sequence of changes:

- (3,1) + (3,)   <- Original shapes
- (3,1) + (1,3)  <- As per rule 1 (add leading dimension to 2nd array)
- (3,3) + (1,3)  <- As per rule 2 (stretch 1st array on axis 1)
- (3,3) + (3,3)  <- As per rule 2 (stretch 2nd array on axis 0)